version: "3.8"
services:
  web:
    build: ./
    image: guns-distribution-web:1.0
    container_name: "guns-distribution-web"
    volumes:
      - "./logs:/runtime/app_logs"
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    environment:
      - ACTIVE=dc
  redis:
    image: redis:6.0
    container_name: "guns-distribution-redis"
    ports:
      - "6380:6379"
    restart: always
    command: redis-server --requirepass 123
  db:
    image: mysql:5.7
    container_name: "guns-distribution-mysql"
    restart: always
    volumes:
      - "./guns_distribution.sql:/docker-entrypoint-initdb.d/db.sql"
      - "/data/mysql/compose-data:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123